// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type BuyDomainsForbiddenType string

const (
	BuyDomainsForbiddenTypeNotAuthorizedForScope BuyDomainsForbiddenType = "not_authorized_for_scope"
	BuyDomainsForbiddenTypeForbidden             BuyDomainsForbiddenType = "forbidden"
)

// BuyDomainsForbidden - NotAuthorizedForScope
type BuyDomainsForbidden struct {
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	ForbiddenError             *ForbiddenError             `queryParam:"inline"`

	Type BuyDomainsForbiddenType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &BuyDomainsForbidden{}

func CreateBuyDomainsForbiddenNotAuthorizedForScope(notAuthorizedForScope NotAuthorizedForScopeError) BuyDomainsForbidden {
	typ := BuyDomainsForbiddenTypeNotAuthorizedForScope

	return BuyDomainsForbidden{
		NotAuthorizedForScopeError: &notAuthorizedForScope,
		Type:                       typ,
	}
}

func CreateBuyDomainsForbiddenForbidden(forbidden ForbiddenError) BuyDomainsForbidden {
	typ := BuyDomainsForbiddenTypeForbidden

	return BuyDomainsForbidden{
		ForbiddenError: &forbidden,
		Type:           typ,
	}
}

func (u *BuyDomainsForbidden) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Code string `json:"code"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Code {
	case "not_authorized_for_scope":
		notAuthorizedForScopeError := new(NotAuthorizedForScopeError)
		if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Code == not_authorized_for_scope) type NotAuthorizedForScopeError within BuyDomainsForbidden: %w", string(data), err)
		}

		u.NotAuthorizedForScopeError = notAuthorizedForScopeError
		u.Type = BuyDomainsForbiddenTypeNotAuthorizedForScope
		return nil
	case "forbidden":
		forbiddenError := new(ForbiddenError)
		if err := utils.UnmarshalJSON(data, &forbiddenError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Code == forbidden) type ForbiddenError within BuyDomainsForbidden: %w", string(data), err)
		}

		u.ForbiddenError = forbiddenError
		u.Type = BuyDomainsForbiddenTypeForbidden
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for BuyDomainsForbidden", string(data))
}

func (u BuyDomainsForbidden) MarshalJSON() ([]byte, error) {
	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.ForbiddenError != nil {
		return utils.MarshalJSON(u.ForbiddenError, "", true)
	}

	return nil, errors.New("could not marshal union type BuyDomainsForbidden: all fields are null")
}

func (u BuyDomainsForbidden) Error() string {
	switch u.Type {
	case BuyDomainsForbiddenTypeNotAuthorizedForScope:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case BuyDomainsForbiddenTypeForbidden:
		data, _ := json.Marshal(u.ForbiddenError)
		return string(data)
	default:
		return "unknown error"
	}
}
