// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type BuyDomainsForbiddenType string

const (
	BuyDomainsForbiddenTypeNotAuthorizedForScopeError BuyDomainsForbiddenType = "NotAuthorizedForScope_error"
	BuyDomainsForbiddenTypeForbiddenError             BuyDomainsForbiddenType = "Forbidden_error"
)

// BuyDomainsForbidden - NotAuthorizedForScope
type BuyDomainsForbidden struct {
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	ForbiddenError             *ForbiddenError             `queryParam:"inline"`

	Type BuyDomainsForbiddenType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &BuyDomainsForbidden{}

func CreateBuyDomainsForbiddenNotAuthorizedForScopeError(notAuthorizedForScopeError NotAuthorizedForScopeError) BuyDomainsForbidden {
	typ := BuyDomainsForbiddenTypeNotAuthorizedForScopeError

	return BuyDomainsForbidden{
		NotAuthorizedForScopeError: &notAuthorizedForScopeError,
		Type:                       typ,
	}
}

func CreateBuyDomainsForbiddenForbiddenError(forbiddenError ForbiddenError) BuyDomainsForbidden {
	typ := BuyDomainsForbiddenTypeForbiddenError

	return BuyDomainsForbidden{
		ForbiddenError: &forbiddenError,
		Type:           typ,
	}
}

func (u *BuyDomainsForbidden) UnmarshalJSON(data []byte) error {

	var notAuthorizedForScopeError NotAuthorizedForScopeError = NotAuthorizedForScopeError{}
	if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err == nil {
		u.NotAuthorizedForScopeError = &notAuthorizedForScopeError
		u.Type = BuyDomainsForbiddenTypeNotAuthorizedForScopeError
		return nil
	}

	var forbiddenError ForbiddenError = ForbiddenError{}
	if err := utils.UnmarshalJSON(data, &forbiddenError, "", true, nil); err == nil {
		u.ForbiddenError = &forbiddenError
		u.Type = BuyDomainsForbiddenTypeForbiddenError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for BuyDomainsForbidden", string(data))
}

func (u BuyDomainsForbidden) MarshalJSON() ([]byte, error) {
	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.ForbiddenError != nil {
		return utils.MarshalJSON(u.ForbiddenError, "", true)
	}

	return nil, errors.New("could not marshal union type BuyDomainsForbidden: all fields are null")
}

func (u BuyDomainsForbidden) Error() string {
	switch u.Type {
	case BuyDomainsForbiddenTypeNotAuthorizedForScopeError:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case BuyDomainsForbiddenTypeForbiddenError:
		data, _ := json.Marshal(u.ForbiddenError)
		return string(data)
	default:
		return "unknown error"
	}
}
