// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type BuySingleDomainForbiddenType string

const (
	BuySingleDomainForbiddenTypeNotAuthorizedForScope BuySingleDomainForbiddenType = "not_authorized_for_scope"
	BuySingleDomainForbiddenTypeForbidden             BuySingleDomainForbiddenType = "forbidden"
)

// BuySingleDomainForbidden - NotAuthorizedForScope
type BuySingleDomainForbidden struct {
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	ForbiddenError             *ForbiddenError             `queryParam:"inline"`

	Type BuySingleDomainForbiddenType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &BuySingleDomainForbidden{}

func CreateBuySingleDomainForbiddenNotAuthorizedForScope(notAuthorizedForScope NotAuthorizedForScopeError) BuySingleDomainForbidden {
	typ := BuySingleDomainForbiddenTypeNotAuthorizedForScope

	return BuySingleDomainForbidden{
		NotAuthorizedForScopeError: &notAuthorizedForScope,
		Type:                       typ,
	}
}

func CreateBuySingleDomainForbiddenForbidden(forbidden ForbiddenError) BuySingleDomainForbidden {
	typ := BuySingleDomainForbiddenTypeForbidden

	return BuySingleDomainForbidden{
		ForbiddenError: &forbidden,
		Type:           typ,
	}
}

func (u *BuySingleDomainForbidden) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Code string `json:"code"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Code {
	case "not_authorized_for_scope":
		notAuthorizedForScopeError := new(NotAuthorizedForScopeError)
		if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Code == not_authorized_for_scope) type NotAuthorizedForScopeError within BuySingleDomainForbidden: %w", string(data), err)
		}

		u.NotAuthorizedForScopeError = notAuthorizedForScopeError
		u.Type = BuySingleDomainForbiddenTypeNotAuthorizedForScope
		return nil
	case "forbidden":
		forbiddenError := new(ForbiddenError)
		if err := utils.UnmarshalJSON(data, &forbiddenError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Code == forbidden) type ForbiddenError within BuySingleDomainForbidden: %w", string(data), err)
		}

		u.ForbiddenError = forbiddenError
		u.Type = BuySingleDomainForbiddenTypeForbidden
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for BuySingleDomainForbidden", string(data))
}

func (u BuySingleDomainForbidden) MarshalJSON() ([]byte, error) {
	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.ForbiddenError != nil {
		return utils.MarshalJSON(u.ForbiddenError, "", true)
	}

	return nil, errors.New("could not marshal union type BuySingleDomainForbidden: all fields are null")
}

func (u BuySingleDomainForbidden) Error() string {
	switch u.Type {
	case BuySingleDomainForbiddenTypeNotAuthorizedForScope:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case BuySingleDomainForbiddenTypeForbidden:
		data, _ := json.Marshal(u.ForbiddenError)
		return string(data)
	default:
		return "unknown error"
	}
}
