// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type GetDomainAuthCodeForbiddenType string

const (
	GetDomainAuthCodeForbiddenTypeNotAuthorizedForScopeError GetDomainAuthCodeForbiddenType = "NotAuthorizedForScope_error"
	GetDomainAuthCodeForbiddenTypeForbiddenError             GetDomainAuthCodeForbiddenType = "Forbidden_error"
)

// GetDomainAuthCodeForbidden - NotAuthorizedForScope
type GetDomainAuthCodeForbidden struct {
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	ForbiddenError             *ForbiddenError             `queryParam:"inline"`

	Type GetDomainAuthCodeForbiddenType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetDomainAuthCodeForbidden{}

func CreateGetDomainAuthCodeForbiddenNotAuthorizedForScopeError(notAuthorizedForScopeError NotAuthorizedForScopeError) GetDomainAuthCodeForbidden {
	typ := GetDomainAuthCodeForbiddenTypeNotAuthorizedForScopeError

	return GetDomainAuthCodeForbidden{
		NotAuthorizedForScopeError: &notAuthorizedForScopeError,
		Type:                       typ,
	}
}

func CreateGetDomainAuthCodeForbiddenForbiddenError(forbiddenError ForbiddenError) GetDomainAuthCodeForbidden {
	typ := GetDomainAuthCodeForbiddenTypeForbiddenError

	return GetDomainAuthCodeForbidden{
		ForbiddenError: &forbiddenError,
		Type:           typ,
	}
}

func (u *GetDomainAuthCodeForbidden) UnmarshalJSON(data []byte) error {

	var notAuthorizedForScopeError NotAuthorizedForScopeError = NotAuthorizedForScopeError{}
	if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err == nil {
		u.NotAuthorizedForScopeError = &notAuthorizedForScopeError
		u.Type = GetDomainAuthCodeForbiddenTypeNotAuthorizedForScopeError
		return nil
	}

	var forbiddenError ForbiddenError = ForbiddenError{}
	if err := utils.UnmarshalJSON(data, &forbiddenError, "", true, nil); err == nil {
		u.ForbiddenError = &forbiddenError
		u.Type = GetDomainAuthCodeForbiddenTypeForbiddenError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetDomainAuthCodeForbidden", string(data))
}

func (u GetDomainAuthCodeForbidden) MarshalJSON() ([]byte, error) {
	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.ForbiddenError != nil {
		return utils.MarshalJSON(u.ForbiddenError, "", true)
	}

	return nil, errors.New("could not marshal union type GetDomainAuthCodeForbidden: all fields are null")
}

func (u GetDomainAuthCodeForbidden) Error() string {
	switch u.Type {
	case GetDomainAuthCodeForbiddenTypeNotAuthorizedForScopeError:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case GetDomainAuthCodeForbiddenTypeForbiddenError:
		data, _ := json.Marshal(u.ForbiddenError)
		return string(data)
	default:
		return "unknown error"
	}
}
