// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type GetDomainAuthCodeForbiddenType string

const (
	GetDomainAuthCodeForbiddenTypeNotAuthorizedForScope GetDomainAuthCodeForbiddenType = "not_authorized_for_scope"
	GetDomainAuthCodeForbiddenTypeForbidden             GetDomainAuthCodeForbiddenType = "forbidden"
)

// GetDomainAuthCodeForbidden - NotAuthorizedForScope
type GetDomainAuthCodeForbidden struct {
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	ForbiddenError             *ForbiddenError             `queryParam:"inline"`

	Type GetDomainAuthCodeForbiddenType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetDomainAuthCodeForbidden{}

func CreateGetDomainAuthCodeForbiddenNotAuthorizedForScope(notAuthorizedForScope NotAuthorizedForScopeError) GetDomainAuthCodeForbidden {
	typ := GetDomainAuthCodeForbiddenTypeNotAuthorizedForScope

	return GetDomainAuthCodeForbidden{
		NotAuthorizedForScopeError: &notAuthorizedForScope,
		Type:                       typ,
	}
}

func CreateGetDomainAuthCodeForbiddenForbidden(forbidden ForbiddenError) GetDomainAuthCodeForbidden {
	typ := GetDomainAuthCodeForbiddenTypeForbidden

	return GetDomainAuthCodeForbidden{
		ForbiddenError: &forbidden,
		Type:           typ,
	}
}

func (u *GetDomainAuthCodeForbidden) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Code string `json:"code"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Code {
	case "not_authorized_for_scope":
		notAuthorizedForScopeError := new(NotAuthorizedForScopeError)
		if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Code == not_authorized_for_scope) type NotAuthorizedForScopeError within GetDomainAuthCodeForbidden: %w", string(data), err)
		}

		u.NotAuthorizedForScopeError = notAuthorizedForScopeError
		u.Type = GetDomainAuthCodeForbiddenTypeNotAuthorizedForScope
		return nil
	case "forbidden":
		forbiddenError := new(ForbiddenError)
		if err := utils.UnmarshalJSON(data, &forbiddenError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Code == forbidden) type ForbiddenError within GetDomainAuthCodeForbidden: %w", string(data), err)
		}

		u.ForbiddenError = forbiddenError
		u.Type = GetDomainAuthCodeForbiddenTypeForbidden
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetDomainAuthCodeForbidden", string(data))
}

func (u GetDomainAuthCodeForbidden) MarshalJSON() ([]byte, error) {
	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.ForbiddenError != nil {
		return utils.MarshalJSON(u.ForbiddenError, "", true)
	}

	return nil, errors.New("could not marshal union type GetDomainAuthCodeForbidden: all fields are null")
}

func (u GetDomainAuthCodeForbidden) Error() string {
	switch u.Type {
	case GetDomainAuthCodeForbiddenTypeNotAuthorizedForScope:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case GetDomainAuthCodeForbiddenTypeForbidden:
		data, _ := json.Marshal(u.ForbiddenError)
		return string(data)
	default:
		return "unknown error"
	}
}
