// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type RenewDomainForbiddenType string

const (
	RenewDomainForbiddenTypeNotAuthorizedForScopeError RenewDomainForbiddenType = "NotAuthorizedForScope_error"
	RenewDomainForbiddenTypeForbiddenError             RenewDomainForbiddenType = "Forbidden_error"
)

// RenewDomainForbidden - NotAuthorizedForScope
type RenewDomainForbidden struct {
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	ForbiddenError             *ForbiddenError             `queryParam:"inline"`

	Type RenewDomainForbiddenType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &RenewDomainForbidden{}

func CreateRenewDomainForbiddenNotAuthorizedForScopeError(notAuthorizedForScopeError NotAuthorizedForScopeError) RenewDomainForbidden {
	typ := RenewDomainForbiddenTypeNotAuthorizedForScopeError

	return RenewDomainForbidden{
		NotAuthorizedForScopeError: &notAuthorizedForScopeError,
		Type:                       typ,
	}
}

func CreateRenewDomainForbiddenForbiddenError(forbiddenError ForbiddenError) RenewDomainForbidden {
	typ := RenewDomainForbiddenTypeForbiddenError

	return RenewDomainForbidden{
		ForbiddenError: &forbiddenError,
		Type:           typ,
	}
}

func (u *RenewDomainForbidden) UnmarshalJSON(data []byte) error {

	var notAuthorizedForScopeError NotAuthorizedForScopeError = NotAuthorizedForScopeError{}
	if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err == nil {
		u.NotAuthorizedForScopeError = &notAuthorizedForScopeError
		u.Type = RenewDomainForbiddenTypeNotAuthorizedForScopeError
		return nil
	}

	var forbiddenError ForbiddenError = ForbiddenError{}
	if err := utils.UnmarshalJSON(data, &forbiddenError, "", true, nil); err == nil {
		u.ForbiddenError = &forbiddenError
		u.Type = RenewDomainForbiddenTypeForbiddenError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RenewDomainForbidden", string(data))
}

func (u RenewDomainForbidden) MarshalJSON() ([]byte, error) {
	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.ForbiddenError != nil {
		return utils.MarshalJSON(u.ForbiddenError, "", true)
	}

	return nil, errors.New("could not marshal union type RenewDomainForbidden: all fields are null")
}

func (u RenewDomainForbidden) Error() string {
	switch u.Type {
	case RenewDomainForbiddenTypeNotAuthorizedForScopeError:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case RenewDomainForbiddenTypeForbiddenError:
		data, _ := json.Marshal(u.ForbiddenError)
		return string(data)
	default:
		return "unknown error"
	}
}
