// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type RenewDomainForbiddenType string

const (
	RenewDomainForbiddenTypeNotAuthorizedForScope RenewDomainForbiddenType = "not_authorized_for_scope"
	RenewDomainForbiddenTypeForbidden             RenewDomainForbiddenType = "forbidden"
)

// RenewDomainForbidden - NotAuthorizedForScope
type RenewDomainForbidden struct {
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	ForbiddenError             *ForbiddenError             `queryParam:"inline"`

	Type RenewDomainForbiddenType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &RenewDomainForbidden{}

func CreateRenewDomainForbiddenNotAuthorizedForScope(notAuthorizedForScope NotAuthorizedForScopeError) RenewDomainForbidden {
	typ := RenewDomainForbiddenTypeNotAuthorizedForScope

	return RenewDomainForbidden{
		NotAuthorizedForScopeError: &notAuthorizedForScope,
		Type:                       typ,
	}
}

func CreateRenewDomainForbiddenForbidden(forbidden ForbiddenError) RenewDomainForbidden {
	typ := RenewDomainForbiddenTypeForbidden

	return RenewDomainForbidden{
		ForbiddenError: &forbidden,
		Type:           typ,
	}
}

func (u *RenewDomainForbidden) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Code string `json:"code"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Code {
	case "not_authorized_for_scope":
		notAuthorizedForScopeError := new(NotAuthorizedForScopeError)
		if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Code == not_authorized_for_scope) type NotAuthorizedForScopeError within RenewDomainForbidden: %w", string(data), err)
		}

		u.NotAuthorizedForScopeError = notAuthorizedForScopeError
		u.Type = RenewDomainForbiddenTypeNotAuthorizedForScope
		return nil
	case "forbidden":
		forbiddenError := new(ForbiddenError)
		if err := utils.UnmarshalJSON(data, &forbiddenError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Code == forbidden) type ForbiddenError within RenewDomainForbidden: %w", string(data), err)
		}

		u.ForbiddenError = forbiddenError
		u.Type = RenewDomainForbiddenTypeForbidden
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RenewDomainForbidden", string(data))
}

func (u RenewDomainForbidden) MarshalJSON() ([]byte, error) {
	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.ForbiddenError != nil {
		return utils.MarshalJSON(u.ForbiddenError, "", true)
	}

	return nil, errors.New("could not marshal union type RenewDomainForbidden: all fields are null")
}

func (u RenewDomainForbidden) Error() string {
	switch u.Type {
	case RenewDomainForbiddenTypeNotAuthorizedForScope:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case RenewDomainForbiddenTypeForbidden:
		data, _ := json.Marshal(u.ForbiddenError)
		return string(data)
	default:
		return "unknown error"
	}
}
