// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type TransferInDomainForbiddenType string

const (
	TransferInDomainForbiddenTypeNotAuthorizedForScopeError TransferInDomainForbiddenType = "NotAuthorizedForScope_error"
	TransferInDomainForbiddenTypeForbiddenError             TransferInDomainForbiddenType = "Forbidden_error"
)

// TransferInDomainForbidden - NotAuthorizedForScope
type TransferInDomainForbidden struct {
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	ForbiddenError             *ForbiddenError             `queryParam:"inline"`

	Type TransferInDomainForbiddenType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &TransferInDomainForbidden{}

func CreateTransferInDomainForbiddenNotAuthorizedForScopeError(notAuthorizedForScopeError NotAuthorizedForScopeError) TransferInDomainForbidden {
	typ := TransferInDomainForbiddenTypeNotAuthorizedForScopeError

	return TransferInDomainForbidden{
		NotAuthorizedForScopeError: &notAuthorizedForScopeError,
		Type:                       typ,
	}
}

func CreateTransferInDomainForbiddenForbiddenError(forbiddenError ForbiddenError) TransferInDomainForbidden {
	typ := TransferInDomainForbiddenTypeForbiddenError

	return TransferInDomainForbidden{
		ForbiddenError: &forbiddenError,
		Type:           typ,
	}
}

func (u *TransferInDomainForbidden) UnmarshalJSON(data []byte) error {

	var notAuthorizedForScopeError NotAuthorizedForScopeError = NotAuthorizedForScopeError{}
	if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err == nil {
		u.NotAuthorizedForScopeError = &notAuthorizedForScopeError
		u.Type = TransferInDomainForbiddenTypeNotAuthorizedForScopeError
		return nil
	}

	var forbiddenError ForbiddenError = ForbiddenError{}
	if err := utils.UnmarshalJSON(data, &forbiddenError, "", true, nil); err == nil {
		u.ForbiddenError = &forbiddenError
		u.Type = TransferInDomainForbiddenTypeForbiddenError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for TransferInDomainForbidden", string(data))
}

func (u TransferInDomainForbidden) MarshalJSON() ([]byte, error) {
	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.ForbiddenError != nil {
		return utils.MarshalJSON(u.ForbiddenError, "", true)
	}

	return nil, errors.New("could not marshal union type TransferInDomainForbidden: all fields are null")
}

func (u TransferInDomainForbidden) Error() string {
	switch u.Type {
	case TransferInDomainForbiddenTypeNotAuthorizedForScopeError:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case TransferInDomainForbiddenTypeForbiddenError:
		data, _ := json.Marshal(u.ForbiddenError)
		return string(data)
	default:
		return "unknown error"
	}
}
