// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type TransferInDomainForbiddenType string

const (
	TransferInDomainForbiddenTypeNotAuthorizedForScope TransferInDomainForbiddenType = "not_authorized_for_scope"
	TransferInDomainForbiddenTypeForbidden             TransferInDomainForbiddenType = "forbidden"
)

// TransferInDomainForbidden - NotAuthorizedForScope
type TransferInDomainForbidden struct {
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	ForbiddenError             *ForbiddenError             `queryParam:"inline"`

	Type TransferInDomainForbiddenType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &TransferInDomainForbidden{}

func CreateTransferInDomainForbiddenNotAuthorizedForScope(notAuthorizedForScope NotAuthorizedForScopeError) TransferInDomainForbidden {
	typ := TransferInDomainForbiddenTypeNotAuthorizedForScope

	return TransferInDomainForbidden{
		NotAuthorizedForScopeError: &notAuthorizedForScope,
		Type:                       typ,
	}
}

func CreateTransferInDomainForbiddenForbidden(forbidden ForbiddenError) TransferInDomainForbidden {
	typ := TransferInDomainForbiddenTypeForbidden

	return TransferInDomainForbidden{
		ForbiddenError: &forbidden,
		Type:           typ,
	}
}

func (u *TransferInDomainForbidden) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Code string `json:"code"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Code {
	case "not_authorized_for_scope":
		notAuthorizedForScopeError := new(NotAuthorizedForScopeError)
		if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Code == not_authorized_for_scope) type NotAuthorizedForScopeError within TransferInDomainForbidden: %w", string(data), err)
		}

		u.NotAuthorizedForScopeError = notAuthorizedForScopeError
		u.Type = TransferInDomainForbiddenTypeNotAuthorizedForScope
		return nil
	case "forbidden":
		forbiddenError := new(ForbiddenError)
		if err := utils.UnmarshalJSON(data, &forbiddenError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Code == forbidden) type ForbiddenError within TransferInDomainForbidden: %w", string(data), err)
		}

		u.ForbiddenError = forbiddenError
		u.Type = TransferInDomainForbiddenTypeForbidden
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for TransferInDomainForbidden", string(data))
}

func (u TransferInDomainForbidden) MarshalJSON() ([]byte, error) {
	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.ForbiddenError != nil {
		return utils.MarshalJSON(u.ForbiddenError, "", true)
	}

	return nil, errors.New("could not marshal union type TransferInDomainForbidden: all fields are null")
}

func (u TransferInDomainForbidden) Error() string {
	switch u.Type {
	case TransferInDomainForbiddenTypeNotAuthorizedForScope:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case TransferInDomainForbiddenTypeForbidden:
		data, _ := json.Marshal(u.ForbiddenError)
		return string(data)
	default:
		return "unknown error"
	}
}
