// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type UpdateDomainAutoRenewForbiddenType string

const (
	UpdateDomainAutoRenewForbiddenTypeNotAuthorizedForScope UpdateDomainAutoRenewForbiddenType = "not_authorized_for_scope"
	UpdateDomainAutoRenewForbiddenTypeForbidden             UpdateDomainAutoRenewForbiddenType = "forbidden"
)

// UpdateDomainAutoRenewForbidden - NotAuthorizedForScope
type UpdateDomainAutoRenewForbidden struct {
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	ForbiddenError             *ForbiddenError             `queryParam:"inline"`

	Type UpdateDomainAutoRenewForbiddenType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateDomainAutoRenewForbidden{}

func CreateUpdateDomainAutoRenewForbiddenNotAuthorizedForScope(notAuthorizedForScope NotAuthorizedForScopeError) UpdateDomainAutoRenewForbidden {
	typ := UpdateDomainAutoRenewForbiddenTypeNotAuthorizedForScope

	return UpdateDomainAutoRenewForbidden{
		NotAuthorizedForScopeError: &notAuthorizedForScope,
		Type:                       typ,
	}
}

func CreateUpdateDomainAutoRenewForbiddenForbidden(forbidden ForbiddenError) UpdateDomainAutoRenewForbidden {
	typ := UpdateDomainAutoRenewForbiddenTypeForbidden

	return UpdateDomainAutoRenewForbidden{
		ForbiddenError: &forbidden,
		Type:           typ,
	}
}

func (u *UpdateDomainAutoRenewForbidden) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Code string `json:"code"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Code {
	case "not_authorized_for_scope":
		notAuthorizedForScopeError := new(NotAuthorizedForScopeError)
		if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Code == not_authorized_for_scope) type NotAuthorizedForScopeError within UpdateDomainAutoRenewForbidden: %w", string(data), err)
		}

		u.NotAuthorizedForScopeError = notAuthorizedForScopeError
		u.Type = UpdateDomainAutoRenewForbiddenTypeNotAuthorizedForScope
		return nil
	case "forbidden":
		forbiddenError := new(ForbiddenError)
		if err := utils.UnmarshalJSON(data, &forbiddenError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Code == forbidden) type ForbiddenError within UpdateDomainAutoRenewForbidden: %w", string(data), err)
		}

		u.ForbiddenError = forbiddenError
		u.Type = UpdateDomainAutoRenewForbiddenTypeForbidden
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateDomainAutoRenewForbidden", string(data))
}

func (u UpdateDomainAutoRenewForbidden) MarshalJSON() ([]byte, error) {
	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.ForbiddenError != nil {
		return utils.MarshalJSON(u.ForbiddenError, "", true)
	}

	return nil, errors.New("could not marshal union type UpdateDomainAutoRenewForbidden: all fields are null")
}

func (u UpdateDomainAutoRenewForbidden) Error() string {
	switch u.Type {
	case UpdateDomainAutoRenewForbiddenTypeNotAuthorizedForScope:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case UpdateDomainAutoRenewForbiddenTypeForbidden:
		data, _ := json.Marshal(u.ForbiddenError)
		return string(data)
	default:
		return "unknown error"
	}
}
