// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type UpdateDomainNameserversForbiddenType string

const (
	UpdateDomainNameserversForbiddenTypeNotAuthorizedForScope UpdateDomainNameserversForbiddenType = "not_authorized_for_scope"
	UpdateDomainNameserversForbiddenTypeForbidden             UpdateDomainNameserversForbiddenType = "forbidden"
)

// UpdateDomainNameserversForbidden - NotAuthorizedForScope
type UpdateDomainNameserversForbidden struct {
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	ForbiddenError             *ForbiddenError             `queryParam:"inline"`

	Type UpdateDomainNameserversForbiddenType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateDomainNameserversForbidden{}

func CreateUpdateDomainNameserversForbiddenNotAuthorizedForScope(notAuthorizedForScope NotAuthorizedForScopeError) UpdateDomainNameserversForbidden {
	typ := UpdateDomainNameserversForbiddenTypeNotAuthorizedForScope

	return UpdateDomainNameserversForbidden{
		NotAuthorizedForScopeError: &notAuthorizedForScope,
		Type:                       typ,
	}
}

func CreateUpdateDomainNameserversForbiddenForbidden(forbidden ForbiddenError) UpdateDomainNameserversForbidden {
	typ := UpdateDomainNameserversForbiddenTypeForbidden

	return UpdateDomainNameserversForbidden{
		ForbiddenError: &forbidden,
		Type:           typ,
	}
}

func (u *UpdateDomainNameserversForbidden) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Code string `json:"code"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Code {
	case "not_authorized_for_scope":
		notAuthorizedForScopeError := new(NotAuthorizedForScopeError)
		if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Code == not_authorized_for_scope) type NotAuthorizedForScopeError within UpdateDomainNameserversForbidden: %w", string(data), err)
		}

		u.NotAuthorizedForScopeError = notAuthorizedForScopeError
		u.Type = UpdateDomainNameserversForbiddenTypeNotAuthorizedForScope
		return nil
	case "forbidden":
		forbiddenError := new(ForbiddenError)
		if err := utils.UnmarshalJSON(data, &forbiddenError, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Code == forbidden) type ForbiddenError within UpdateDomainNameserversForbidden: %w", string(data), err)
		}

		u.ForbiddenError = forbiddenError
		u.Type = UpdateDomainNameserversForbiddenTypeForbidden
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateDomainNameserversForbidden", string(data))
}

func (u UpdateDomainNameserversForbidden) MarshalJSON() ([]byte, error) {
	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.ForbiddenError != nil {
		return utils.MarshalJSON(u.ForbiddenError, "", true)
	}

	return nil, errors.New("could not marshal union type UpdateDomainNameserversForbidden: all fields are null")
}

func (u UpdateDomainNameserversForbidden) Error() string {
	switch u.Type {
	case UpdateDomainNameserversForbiddenTypeNotAuthorizedForScope:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case UpdateDomainNameserversForbiddenTypeForbidden:
		data, _ := json.Marshal(u.ForbiddenError)
		return string(data)
	default:
		return "unknown error"
	}
}
