// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type UpdateDomainAutoRenewForbiddenType string

const (
	UpdateDomainAutoRenewForbiddenTypeNotAuthorizedForScopeError UpdateDomainAutoRenewForbiddenType = "NotAuthorizedForScope_error"
	UpdateDomainAutoRenewForbiddenTypeForbiddenError             UpdateDomainAutoRenewForbiddenType = "Forbidden_error"
)

// UpdateDomainAutoRenewForbidden - NotAuthorizedForScope
type UpdateDomainAutoRenewForbidden struct {
	NotAuthorizedForScopeError *NotAuthorizedForScopeError `queryParam:"inline"`
	ForbiddenError             *ForbiddenError             `queryParam:"inline"`

	Type UpdateDomainAutoRenewForbiddenType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateDomainAutoRenewForbidden{}

func CreateUpdateDomainAutoRenewForbiddenNotAuthorizedForScopeError(notAuthorizedForScopeError NotAuthorizedForScopeError) UpdateDomainAutoRenewForbidden {
	typ := UpdateDomainAutoRenewForbiddenTypeNotAuthorizedForScopeError

	return UpdateDomainAutoRenewForbidden{
		NotAuthorizedForScopeError: &notAuthorizedForScopeError,
		Type:                       typ,
	}
}

func CreateUpdateDomainAutoRenewForbiddenForbiddenError(forbiddenError ForbiddenError) UpdateDomainAutoRenewForbidden {
	typ := UpdateDomainAutoRenewForbiddenTypeForbiddenError

	return UpdateDomainAutoRenewForbidden{
		ForbiddenError: &forbiddenError,
		Type:           typ,
	}
}

func (u *UpdateDomainAutoRenewForbidden) UnmarshalJSON(data []byte) error {

	var notAuthorizedForScopeError NotAuthorizedForScopeError = NotAuthorizedForScopeError{}
	if err := utils.UnmarshalJSON(data, &notAuthorizedForScopeError, "", true, nil); err == nil {
		u.NotAuthorizedForScopeError = &notAuthorizedForScopeError
		u.Type = UpdateDomainAutoRenewForbiddenTypeNotAuthorizedForScopeError
		return nil
	}

	var forbiddenError ForbiddenError = ForbiddenError{}
	if err := utils.UnmarshalJSON(data, &forbiddenError, "", true, nil); err == nil {
		u.ForbiddenError = &forbiddenError
		u.Type = UpdateDomainAutoRenewForbiddenTypeForbiddenError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateDomainAutoRenewForbidden", string(data))
}

func (u UpdateDomainAutoRenewForbidden) MarshalJSON() ([]byte, error) {
	if u.NotAuthorizedForScopeError != nil {
		return utils.MarshalJSON(u.NotAuthorizedForScopeError, "", true)
	}

	if u.ForbiddenError != nil {
		return utils.MarshalJSON(u.ForbiddenError, "", true)
	}

	return nil, errors.New("could not marshal union type UpdateDomainAutoRenewForbidden: all fields are null")
}

func (u UpdateDomainAutoRenewForbidden) Error() string {
	switch u.Type {
	case UpdateDomainAutoRenewForbiddenTypeNotAuthorizedForScopeError:
		data, _ := json.Marshal(u.NotAuthorizedForScopeError)
		return string(data)
	case UpdateDomainAutoRenewForbiddenTypeForbiddenError:
		data, _ := json.Marshal(u.ForbiddenError)
		return string(data)
	default:
		return "unknown error"
	}
}
