/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Forbidden,
  Forbidden$inboundSchema,
  Forbidden$Outbound,
  Forbidden$outboundSchema,
} from "./forbidden.js";
import {
  NotAuthorizedForScope,
  NotAuthorizedForScope$inboundSchema,
  NotAuthorizedForScope$Outbound,
  NotAuthorizedForScope$outboundSchema,
} from "./notauthorizedforscope.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type Additional = {};

/**
 * The contact information for the domain. Some TLDs require additional contact information. Use the [Get contact info schema](https://vercel.com/docs/rest-api/reference/endpoints/domains-registrar/get-contact-info-schema) endpoint to retrieve the required fields.
 */
export type ContactInformation = {
  /**
   * a non empty string
   */
  firstName: string;
  /**
   * a non empty string
   */
  lastName: string;
  /**
   * a non empty string
   */
  email: string;
  /**
   * A valid E.164 phone number
   */
  phone: string;
  /**
   * a non empty string
   */
  address1: string;
  /**
   * a non empty string
   */
  address2?: string | undefined;
  /**
   * a non empty string
   */
  city: string;
  /**
   * a non empty string
   */
  state: string;
  /**
   * a non empty string
   */
  zip: string;
  /**
   * A valid ISO 3166-1 alpha-2 country code
   */
  country: string;
  /**
   * a non empty string
   */
  companyName?: string | undefined;
  /**
   * A valid E.164 phone number
   */
  fax?: string | undefined;
  additional?: Additional | undefined;
};

export type BuySingleDomainRequestBody = {
  /**
   * Whether the domain should be auto-renewed before it expires. This can be configured later through the Vercel Dashboard or the [Update auto-renew for a domain](https://vercel.com/docs/rest-api/reference/endpoints/domains-registrar/update-auto-renew-for-a-domain) endpoint.
   */
  autoRenew: boolean;
  /**
   * The number of years to purchase the domain for.
   */
  years: number;
  /**
   * The expected price for the domain. Use the [Get price data for a domain](https://vercel.com/docs/rest-api/reference/endpoints/domains-registrar/get-price-data-for-a-domain) endpoint to retrieve the price data for a domain.
   */
  expectedPrice: number;
  /**
   * The contact information for the domain. Some TLDs require additional contact information. Use the [Get contact info schema](https://vercel.com/docs/rest-api/reference/endpoints/domains-registrar/get-contact-info-schema) endpoint to retrieve the required fields.
   */
  contactInformation: ContactInformation;
};

export type BuySingleDomainRequest = {
  domain: string;
  teamId?: string | undefined;
  requestBody: BuySingleDomainRequestBody;
};

/**
 * NotAuthorizedForScope
 */
export type BuySingleDomainDomainsRegistrarResponseBody =
  | NotAuthorizedForScope
  | Forbidden;

export const BuySingleDomainMethod = {
  Get: "GET",
  Post: "POST",
  Put: "PUT",
  Delete: "DELETE",
  Patch: "PATCH",
} as const;
export type BuySingleDomainMethod = ClosedEnum<typeof BuySingleDomainMethod>;

export type Links = {
  href: string;
  method: BuySingleDomainMethod;
};

/**
 * Success
 */
export type BuySingleDomainResponseBody = {
  orderId: string;
  links: { [k: string]: Links };
};

/** @internal */
export const Additional$inboundSchema: z.ZodType<
  Additional,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type Additional$Outbound = {};

/** @internal */
export const Additional$outboundSchema: z.ZodType<
  Additional$Outbound,
  z.ZodTypeDef,
  Additional
> = z.object({});

export function additionalToJSON(additional: Additional): string {
  return JSON.stringify(Additional$outboundSchema.parse(additional));
}
export function additionalFromJSON(
  jsonString: string,
): SafeParseResult<Additional, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Additional$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Additional' from JSON`,
  );
}

/** @internal */
export const ContactInformation$inboundSchema: z.ZodType<
  ContactInformation,
  z.ZodTypeDef,
  unknown
> = z.object({
  firstName: z.string(),
  lastName: z.string(),
  email: z.string(),
  phone: z.string(),
  address1: z.string(),
  address2: z.string().optional(),
  city: z.string(),
  state: z.string(),
  zip: z.string(),
  country: z.string(),
  companyName: z.string().optional(),
  fax: z.string().optional(),
  additional: z.lazy(() => Additional$inboundSchema).optional(),
});
/** @internal */
export type ContactInformation$Outbound = {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  address1: string;
  address2?: string | undefined;
  city: string;
  state: string;
  zip: string;
  country: string;
  companyName?: string | undefined;
  fax?: string | undefined;
  additional?: Additional$Outbound | undefined;
};

/** @internal */
export const ContactInformation$outboundSchema: z.ZodType<
  ContactInformation$Outbound,
  z.ZodTypeDef,
  ContactInformation
> = z.object({
  firstName: z.string(),
  lastName: z.string(),
  email: z.string(),
  phone: z.string(),
  address1: z.string(),
  address2: z.string().optional(),
  city: z.string(),
  state: z.string(),
  zip: z.string(),
  country: z.string(),
  companyName: z.string().optional(),
  fax: z.string().optional(),
  additional: z.lazy(() => Additional$outboundSchema).optional(),
});

export function contactInformationToJSON(
  contactInformation: ContactInformation,
): string {
  return JSON.stringify(
    ContactInformation$outboundSchema.parse(contactInformation),
  );
}
export function contactInformationFromJSON(
  jsonString: string,
): SafeParseResult<ContactInformation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContactInformation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContactInformation' from JSON`,
  );
}

/** @internal */
export const BuySingleDomainRequestBody$inboundSchema: z.ZodType<
  BuySingleDomainRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  autoRenew: z.boolean(),
  years: z.number(),
  expectedPrice: z.number(),
  contactInformation: z.lazy(() => ContactInformation$inboundSchema),
});
/** @internal */
export type BuySingleDomainRequestBody$Outbound = {
  autoRenew: boolean;
  years: number;
  expectedPrice: number;
  contactInformation: ContactInformation$Outbound;
};

/** @internal */
export const BuySingleDomainRequestBody$outboundSchema: z.ZodType<
  BuySingleDomainRequestBody$Outbound,
  z.ZodTypeDef,
  BuySingleDomainRequestBody
> = z.object({
  autoRenew: z.boolean(),
  years: z.number(),
  expectedPrice: z.number(),
  contactInformation: z.lazy(() => ContactInformation$outboundSchema),
});

export function buySingleDomainRequestBodyToJSON(
  buySingleDomainRequestBody: BuySingleDomainRequestBody,
): string {
  return JSON.stringify(
    BuySingleDomainRequestBody$outboundSchema.parse(buySingleDomainRequestBody),
  );
}
export function buySingleDomainRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<BuySingleDomainRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BuySingleDomainRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BuySingleDomainRequestBody' from JSON`,
  );
}

/** @internal */
export const BuySingleDomainRequest$inboundSchema: z.ZodType<
  BuySingleDomainRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  domain: z.string(),
  teamId: z.string().optional(),
  RequestBody: z.lazy(() => BuySingleDomainRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type BuySingleDomainRequest$Outbound = {
  domain: string;
  teamId?: string | undefined;
  RequestBody: BuySingleDomainRequestBody$Outbound;
};

/** @internal */
export const BuySingleDomainRequest$outboundSchema: z.ZodType<
  BuySingleDomainRequest$Outbound,
  z.ZodTypeDef,
  BuySingleDomainRequest
> = z.object({
  domain: z.string(),
  teamId: z.string().optional(),
  requestBody: z.lazy(() => BuySingleDomainRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function buySingleDomainRequestToJSON(
  buySingleDomainRequest: BuySingleDomainRequest,
): string {
  return JSON.stringify(
    BuySingleDomainRequest$outboundSchema.parse(buySingleDomainRequest),
  );
}
export function buySingleDomainRequestFromJSON(
  jsonString: string,
): SafeParseResult<BuySingleDomainRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BuySingleDomainRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BuySingleDomainRequest' from JSON`,
  );
}

/** @internal */
export const BuySingleDomainDomainsRegistrarResponseBody$inboundSchema:
  z.ZodType<
    BuySingleDomainDomainsRegistrarResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.union([NotAuthorizedForScope$inboundSchema, Forbidden$inboundSchema]);
/** @internal */
export type BuySingleDomainDomainsRegistrarResponseBody$Outbound =
  | NotAuthorizedForScope$Outbound
  | Forbidden$Outbound;

/** @internal */
export const BuySingleDomainDomainsRegistrarResponseBody$outboundSchema:
  z.ZodType<
    BuySingleDomainDomainsRegistrarResponseBody$Outbound,
    z.ZodTypeDef,
    unknown
  > = z.union([NotAuthorizedForScope$outboundSchema, Forbidden$outboundSchema]);

export function buySingleDomainDomainsRegistrarResponseBodyToJSON(
  buySingleDomainDomainsRegistrarResponseBody:
    BuySingleDomainDomainsRegistrarResponseBody,
): string {
  return JSON.stringify(
    BuySingleDomainDomainsRegistrarResponseBody$outboundSchema.parse(
      buySingleDomainDomainsRegistrarResponseBody,
    ),
  );
}
export function buySingleDomainDomainsRegistrarResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  BuySingleDomainDomainsRegistrarResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      BuySingleDomainDomainsRegistrarResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'BuySingleDomainDomainsRegistrarResponseBody' from JSON`,
  );
}

/** @internal */
export const BuySingleDomainMethod$inboundSchema: z.ZodNativeEnum<
  typeof BuySingleDomainMethod
> = z.nativeEnum(BuySingleDomainMethod);
/** @internal */
export const BuySingleDomainMethod$outboundSchema: z.ZodNativeEnum<
  typeof BuySingleDomainMethod
> = BuySingleDomainMethod$inboundSchema;

/** @internal */
export const Links$inboundSchema: z.ZodType<Links, z.ZodTypeDef, unknown> = z
  .object({
    href: z.string(),
    method: BuySingleDomainMethod$inboundSchema,
  });
/** @internal */
export type Links$Outbound = {
  href: string;
  method: string;
};

/** @internal */
export const Links$outboundSchema: z.ZodType<
  Links$Outbound,
  z.ZodTypeDef,
  Links
> = z.object({
  href: z.string(),
  method: BuySingleDomainMethod$outboundSchema,
});

export function linksToJSON(links: Links): string {
  return JSON.stringify(Links$outboundSchema.parse(links));
}
export function linksFromJSON(
  jsonString: string,
): SafeParseResult<Links, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Links$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Links' from JSON`,
  );
}

/** @internal */
export const BuySingleDomainResponseBody$inboundSchema: z.ZodType<
  BuySingleDomainResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  orderId: z.string(),
  _links: z.record(z.lazy(() => Links$inboundSchema)),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
  });
});
/** @internal */
export type BuySingleDomainResponseBody$Outbound = {
  orderId: string;
  _links: { [k: string]: Links$Outbound };
};

/** @internal */
export const BuySingleDomainResponseBody$outboundSchema: z.ZodType<
  BuySingleDomainResponseBody$Outbound,
  z.ZodTypeDef,
  BuySingleDomainResponseBody
> = z.object({
  orderId: z.string(),
  links: z.record(z.lazy(() => Links$outboundSchema)),
}).transform((v) => {
  return remap$(v, {
    links: "_links",
  });
});

export function buySingleDomainResponseBodyToJSON(
  buySingleDomainResponseBody: BuySingleDomainResponseBody,
): string {
  return JSON.stringify(
    BuySingleDomainResponseBody$outboundSchema.parse(
      buySingleDomainResponseBody,
    ),
  );
}
export function buySingleDomainResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<BuySingleDomainResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BuySingleDomainResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BuySingleDomainResponseBody' from JSON`,
  );
}
