/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Forbidden,
  Forbidden$inboundSchema,
  Forbidden$Outbound,
  Forbidden$outboundSchema,
} from "./forbidden.js";
import {
  NotAuthorizedForScope,
  NotAuthorizedForScope$inboundSchema,
  NotAuthorizedForScope$Outbound,
  NotAuthorizedForScope$outboundSchema,
} from "./notauthorizedforscope.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type GetDomainAuthCodeRequest = {
  domain: string;
  teamId?: string | undefined;
};

/**
 * NotAuthorizedForScope
 */
export type GetDomainAuthCodeDomainsRegistrarResponseBody =
  | NotAuthorizedForScope
  | Forbidden;

/**
 * Success
 */
export type GetDomainAuthCodeResponseBody = {
  authCode: string;
};

/** @internal */
export const GetDomainAuthCodeRequest$inboundSchema: z.ZodType<
  GetDomainAuthCodeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  domain: z.string(),
  teamId: z.string().optional(),
});
/** @internal */
export type GetDomainAuthCodeRequest$Outbound = {
  domain: string;
  teamId?: string | undefined;
};

/** @internal */
export const GetDomainAuthCodeRequest$outboundSchema: z.ZodType<
  GetDomainAuthCodeRequest$Outbound,
  z.ZodTypeDef,
  GetDomainAuthCodeRequest
> = z.object({
  domain: z.string(),
  teamId: z.string().optional(),
});

export function getDomainAuthCodeRequestToJSON(
  getDomainAuthCodeRequest: GetDomainAuthCodeRequest,
): string {
  return JSON.stringify(
    GetDomainAuthCodeRequest$outboundSchema.parse(getDomainAuthCodeRequest),
  );
}
export function getDomainAuthCodeRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetDomainAuthCodeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDomainAuthCodeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDomainAuthCodeRequest' from JSON`,
  );
}

/** @internal */
export const GetDomainAuthCodeDomainsRegistrarResponseBody$inboundSchema:
  z.ZodType<
    GetDomainAuthCodeDomainsRegistrarResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.union([NotAuthorizedForScope$inboundSchema, Forbidden$inboundSchema]);
/** @internal */
export type GetDomainAuthCodeDomainsRegistrarResponseBody$Outbound =
  | NotAuthorizedForScope$Outbound
  | Forbidden$Outbound;

/** @internal */
export const GetDomainAuthCodeDomainsRegistrarResponseBody$outboundSchema:
  z.ZodType<
    GetDomainAuthCodeDomainsRegistrarResponseBody$Outbound,
    z.ZodTypeDef,
    unknown
  > = z.union([NotAuthorizedForScope$outboundSchema, Forbidden$outboundSchema]);

export function getDomainAuthCodeDomainsRegistrarResponseBodyToJSON(
  getDomainAuthCodeDomainsRegistrarResponseBody:
    GetDomainAuthCodeDomainsRegistrarResponseBody,
): string {
  return JSON.stringify(
    GetDomainAuthCodeDomainsRegistrarResponseBody$outboundSchema.parse(
      getDomainAuthCodeDomainsRegistrarResponseBody,
    ),
  );
}
export function getDomainAuthCodeDomainsRegistrarResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetDomainAuthCodeDomainsRegistrarResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetDomainAuthCodeDomainsRegistrarResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetDomainAuthCodeDomainsRegistrarResponseBody' from JSON`,
  );
}

/** @internal */
export const GetDomainAuthCodeResponseBody$inboundSchema: z.ZodType<
  GetDomainAuthCodeResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  authCode: z.string(),
});
/** @internal */
export type GetDomainAuthCodeResponseBody$Outbound = {
  authCode: string;
};

/** @internal */
export const GetDomainAuthCodeResponseBody$outboundSchema: z.ZodType<
  GetDomainAuthCodeResponseBody$Outbound,
  z.ZodTypeDef,
  GetDomainAuthCodeResponseBody
> = z.object({
  authCode: z.string(),
});

export function getDomainAuthCodeResponseBodyToJSON(
  getDomainAuthCodeResponseBody: GetDomainAuthCodeResponseBody,
): string {
  return JSON.stringify(
    GetDomainAuthCodeResponseBody$outboundSchema.parse(
      getDomainAuthCodeResponseBody,
    ),
  );
}
export function getDomainAuthCodeResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetDomainAuthCodeResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDomainAuthCodeResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDomainAuthCodeResponseBody' from JSON`,
  );
}
