/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type GetDomainPriceRequest = {
  domain: string;
  /**
   * The number of years to get the price for. If not provided, the minimum number of years for the TLD will be used.
   */
  years?: string | undefined;
  teamId?: string | undefined;
};

export type GetDomainPricePurchasePrice = number | string;

export type GetDomainPriceRenewalPrice = number | string;

export type GetDomainPriceTransferPrice = number | string;

/**
 * Success
 */
export type GetDomainPriceResponseBody = {
  years: number;
  purchasePrice: number | string;
  renewalPrice: number | string;
  transferPrice: number | string;
};

/** @internal */
export const GetDomainPriceRequest$inboundSchema: z.ZodType<
  GetDomainPriceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  domain: z.string(),
  years: z.string().optional(),
  teamId: z.string().optional(),
});
/** @internal */
export type GetDomainPriceRequest$Outbound = {
  domain: string;
  years?: string | undefined;
  teamId?: string | undefined;
};

/** @internal */
export const GetDomainPriceRequest$outboundSchema: z.ZodType<
  GetDomainPriceRequest$Outbound,
  z.ZodTypeDef,
  GetDomainPriceRequest
> = z.object({
  domain: z.string(),
  years: z.string().optional(),
  teamId: z.string().optional(),
});

export function getDomainPriceRequestToJSON(
  getDomainPriceRequest: GetDomainPriceRequest,
): string {
  return JSON.stringify(
    GetDomainPriceRequest$outboundSchema.parse(getDomainPriceRequest),
  );
}
export function getDomainPriceRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetDomainPriceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDomainPriceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDomainPriceRequest' from JSON`,
  );
}

/** @internal */
export const GetDomainPricePurchasePrice$inboundSchema: z.ZodType<
  GetDomainPricePurchasePrice,
  z.ZodTypeDef,
  unknown
> = z.union([z.number(), z.string()]);
/** @internal */
export type GetDomainPricePurchasePrice$Outbound = number | string;

/** @internal */
export const GetDomainPricePurchasePrice$outboundSchema: z.ZodType<
  GetDomainPricePurchasePrice$Outbound,
  z.ZodTypeDef,
  GetDomainPricePurchasePrice
> = z.union([z.number(), z.string()]);

export function getDomainPricePurchasePriceToJSON(
  getDomainPricePurchasePrice: GetDomainPricePurchasePrice,
): string {
  return JSON.stringify(
    GetDomainPricePurchasePrice$outboundSchema.parse(
      getDomainPricePurchasePrice,
    ),
  );
}
export function getDomainPricePurchasePriceFromJSON(
  jsonString: string,
): SafeParseResult<GetDomainPricePurchasePrice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDomainPricePurchasePrice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDomainPricePurchasePrice' from JSON`,
  );
}

/** @internal */
export const GetDomainPriceRenewalPrice$inboundSchema: z.ZodType<
  GetDomainPriceRenewalPrice,
  z.ZodTypeDef,
  unknown
> = z.union([z.number(), z.string()]);
/** @internal */
export type GetDomainPriceRenewalPrice$Outbound = number | string;

/** @internal */
export const GetDomainPriceRenewalPrice$outboundSchema: z.ZodType<
  GetDomainPriceRenewalPrice$Outbound,
  z.ZodTypeDef,
  GetDomainPriceRenewalPrice
> = z.union([z.number(), z.string()]);

export function getDomainPriceRenewalPriceToJSON(
  getDomainPriceRenewalPrice: GetDomainPriceRenewalPrice,
): string {
  return JSON.stringify(
    GetDomainPriceRenewalPrice$outboundSchema.parse(getDomainPriceRenewalPrice),
  );
}
export function getDomainPriceRenewalPriceFromJSON(
  jsonString: string,
): SafeParseResult<GetDomainPriceRenewalPrice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDomainPriceRenewalPrice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDomainPriceRenewalPrice' from JSON`,
  );
}

/** @internal */
export const GetDomainPriceTransferPrice$inboundSchema: z.ZodType<
  GetDomainPriceTransferPrice,
  z.ZodTypeDef,
  unknown
> = z.union([z.number(), z.string()]);
/** @internal */
export type GetDomainPriceTransferPrice$Outbound = number | string;

/** @internal */
export const GetDomainPriceTransferPrice$outboundSchema: z.ZodType<
  GetDomainPriceTransferPrice$Outbound,
  z.ZodTypeDef,
  GetDomainPriceTransferPrice
> = z.union([z.number(), z.string()]);

export function getDomainPriceTransferPriceToJSON(
  getDomainPriceTransferPrice: GetDomainPriceTransferPrice,
): string {
  return JSON.stringify(
    GetDomainPriceTransferPrice$outboundSchema.parse(
      getDomainPriceTransferPrice,
    ),
  );
}
export function getDomainPriceTransferPriceFromJSON(
  jsonString: string,
): SafeParseResult<GetDomainPriceTransferPrice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDomainPriceTransferPrice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDomainPriceTransferPrice' from JSON`,
  );
}

/** @internal */
export const GetDomainPriceResponseBody$inboundSchema: z.ZodType<
  GetDomainPriceResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  years: z.number(),
  purchasePrice: z.union([z.number(), z.string()]),
  renewalPrice: z.union([z.number(), z.string()]),
  transferPrice: z.union([z.number(), z.string()]),
});
/** @internal */
export type GetDomainPriceResponseBody$Outbound = {
  years: number;
  purchasePrice: number | string;
  renewalPrice: number | string;
  transferPrice: number | string;
};

/** @internal */
export const GetDomainPriceResponseBody$outboundSchema: z.ZodType<
  GetDomainPriceResponseBody$Outbound,
  z.ZodTypeDef,
  GetDomainPriceResponseBody
> = z.object({
  years: z.number(),
  purchasePrice: z.union([z.number(), z.string()]),
  renewalPrice: z.union([z.number(), z.string()]),
  transferPrice: z.union([z.number(), z.string()]),
});

export function getDomainPriceResponseBodyToJSON(
  getDomainPriceResponseBody: GetDomainPriceResponseBody,
): string {
  return JSON.stringify(
    GetDomainPriceResponseBody$outboundSchema.parse(getDomainPriceResponseBody),
  );
}
export function getDomainPriceResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetDomainPriceResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDomainPriceResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDomainPriceResponseBody' from JSON`,
  );
}
