/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type RateLimitNotice = {
  remaining: number;
  reset: number;
  resetMs: number;
  total: number;
};

/** @internal */
export const RateLimitNotice$inboundSchema: z.ZodType<
  RateLimitNotice,
  z.ZodTypeDef,
  unknown
> = z.object({
  remaining: z.number().int(),
  reset: z.number().int(),
  resetMs: z.number().int(),
  total: z.number().int(),
});
/** @internal */
export type RateLimitNotice$Outbound = {
  remaining: number;
  reset: number;
  resetMs: number;
  total: number;
};

/** @internal */
export const RateLimitNotice$outboundSchema: z.ZodType<
  RateLimitNotice$Outbound,
  z.ZodTypeDef,
  RateLimitNotice
> = z.object({
  remaining: z.number().int(),
  reset: z.number().int(),
  resetMs: z.number().int(),
  total: z.number().int(),
});

export function rateLimitNoticeToJSON(
  rateLimitNotice: RateLimitNotice,
): string {
  return JSON.stringify(RateLimitNotice$outboundSchema.parse(rateLimitNotice));
}
export function rateLimitNoticeFromJSON(
  jsonString: string,
): SafeParseResult<RateLimitNotice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RateLimitNotice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RateLimitNotice' from JSON`,
  );
}
