/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Forbidden,
  Forbidden$inboundSchema,
  Forbidden$Outbound,
  Forbidden$outboundSchema,
} from "./forbidden.js";
import {
  NotAuthorizedForScope,
  NotAuthorizedForScope$inboundSchema,
  NotAuthorizedForScope$Outbound,
  NotAuthorizedForScope$outboundSchema,
} from "./notauthorizedforscope.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type UpdateDomainNameserversRequestBody = {
  nameservers: Array<string>;
};

export type UpdateDomainNameserversRequest = {
  domain: string;
  teamId?: string | undefined;
  requestBody: UpdateDomainNameserversRequestBody;
};

/**
 * NotAuthorizedForScope
 */
export type UpdateDomainNameserversResponseBody =
  | NotAuthorizedForScope
  | Forbidden;

/** @internal */
export const UpdateDomainNameserversRequestBody$inboundSchema: z.ZodType<
  UpdateDomainNameserversRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  nameservers: z.array(z.string()),
});
/** @internal */
export type UpdateDomainNameserversRequestBody$Outbound = {
  nameservers: Array<string>;
};

/** @internal */
export const UpdateDomainNameserversRequestBody$outboundSchema: z.ZodType<
  UpdateDomainNameserversRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateDomainNameserversRequestBody
> = z.object({
  nameservers: z.array(z.string()),
});

export function updateDomainNameserversRequestBodyToJSON(
  updateDomainNameserversRequestBody: UpdateDomainNameserversRequestBody,
): string {
  return JSON.stringify(
    UpdateDomainNameserversRequestBody$outboundSchema.parse(
      updateDomainNameserversRequestBody,
    ),
  );
}
export function updateDomainNameserversRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDomainNameserversRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateDomainNameserversRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDomainNameserversRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdateDomainNameserversRequest$inboundSchema: z.ZodType<
  UpdateDomainNameserversRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  domain: z.string(),
  teamId: z.string().optional(),
  RequestBody: z.lazy(() => UpdateDomainNameserversRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type UpdateDomainNameserversRequest$Outbound = {
  domain: string;
  teamId?: string | undefined;
  RequestBody: UpdateDomainNameserversRequestBody$Outbound;
};

/** @internal */
export const UpdateDomainNameserversRequest$outboundSchema: z.ZodType<
  UpdateDomainNameserversRequest$Outbound,
  z.ZodTypeDef,
  UpdateDomainNameserversRequest
> = z.object({
  domain: z.string(),
  teamId: z.string().optional(),
  requestBody: z.lazy(() => UpdateDomainNameserversRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function updateDomainNameserversRequestToJSON(
  updateDomainNameserversRequest: UpdateDomainNameserversRequest,
): string {
  return JSON.stringify(
    UpdateDomainNameserversRequest$outboundSchema.parse(
      updateDomainNameserversRequest,
    ),
  );
}
export function updateDomainNameserversRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDomainNameserversRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDomainNameserversRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDomainNameserversRequest' from JSON`,
  );
}

/** @internal */
export const UpdateDomainNameserversResponseBody$inboundSchema: z.ZodType<
  UpdateDomainNameserversResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([NotAuthorizedForScope$inboundSchema, Forbidden$inboundSchema]);
/** @internal */
export type UpdateDomainNameserversResponseBody$Outbound =
  | NotAuthorizedForScope$Outbound
  | Forbidden$Outbound;

/** @internal */
export const UpdateDomainNameserversResponseBody$outboundSchema: z.ZodType<
  UpdateDomainNameserversResponseBody$Outbound,
  z.ZodTypeDef,
  unknown
> = z.union([NotAuthorizedForScope$outboundSchema, Forbidden$outboundSchema]);

export function updateDomainNameserversResponseBodyToJSON(
  updateDomainNameserversResponseBody: UpdateDomainNameserversResponseBody,
): string {
  return JSON.stringify(
    UpdateDomainNameserversResponseBody$outboundSchema.parse(
      updateDomainNameserversResponseBody,
    ),
  );
}
export function updateDomainNameserversResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDomainNameserversResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateDomainNameserversResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDomainNameserversResponseBody' from JSON`,
  );
}
